### ISSUE TITLE
Implement log rotation

### ISSUE THREAD

**Issue by jsha** [jsha/blocktogether#125]
Block Together uses log4js for logging, but it doesn't rotate its logs. That means it retains data longer than it should, and it wastes disk space. Instead it should use log4js's rotating file appender, to rotate logs once a day and clean up old ones.

**Comment by binaryparadox** [comment]
@jsha Double checking: is this still Open? I see a [log-lotation branch](https://github.com/jsha/blocktogether/commits/log-rotation) that might be WIP?

**Comment by jsha** [comment]
This is still open the log-rotation branch is fully merged. Not sure what I was doing in that one, probably rotation of nginx logs.

BTW, I am fine either using log4js's log rotation or the system one. Rotation should be daily, cleanup after 30 days.

**Comment by binaryparadox** [comment]
Looking at doing it with Log4js with the [dateFile appender](https://github.com/nomiddlename/log4js-node/wiki/Date-rolling-file-appender). It seems like Example 2 is ~= what you're looking for.

Are you ok with the corner case mentioned at the bottom of the documentation? i.e. For the ``blocktogether-info.log`` if I use `"patern": "--d.log"` in the appender config it'll result in 31 files on disk for this month: ``/data/blocktogether/shared/log/blocktogether-info.log`` will be todays in progress log file,  ``/data/blocktogether/shared/log/blocktogether-info.log-16.log``would be yesterdays, etc. Since next month only has 30 days  ``/data/blocktogether/shared/log/blocktogether-info.log-31.log` will have stale content until it is overwritten on March 31st.

**Comment by binaryparadox** [comment]
Code is merged. Closing this bug.
