### ISSUE TITLE
Bug - TypeError in actions.js on startup

### ISSUE THREAD

**Issue by ccppuu** [jsha/blocktogether#159]
At startup (using the run-dev.sh script from the in-progress vagrant env) there is a TypeError in actions.js

This might be my particular env! It might be fixed already elsewhere! Just want to make sure the stacktrace is here if it ends up being useful.

```
/vagrant/actions.js:487
    var requests = twitter.keepAliveAgent.requests;
                                         ^
TypeError: Cannot read property 'requests' of undefined
    at logPendingRequests (/vagrant/actions.js:487:42)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by doeg** [comment]
I can consistently reproduce this on my end.

**Comment by jsha** [comment]
This is due to the issue I mentioned on the Vagrant branch: you accidentally blew away the local copy of node-twitter-api, which introduces the keepAliveAgent variable.

You should be able to temporarily workaround by changing this to e.g. https.globalAgent.requests (you'll have to include https). I'll work on making the node-twitter-api include better.

**Comment by jsha** [comment]
Fixed.
