### ISSUE TITLE
Friend blocked because of low follwer count?

### ISSUE THREAD

**Issue by ryulong** [jsha/blocktogether#190]
I've got a friend who's got less than 15 followers and constantly shows up as a false positive in the blocktogether.org reports, but today the app somehow blocked him despite the fact I was following him. The screencap below shows all of the blocktogether.org actions on my friend's account over the past few hours.
![ss 2015-05-23 at 07 56 00](https://cloud.githubusercontent.com/assets/12578700/7786131/ca507430-0185-11e5-964b-766d7146b82a.png)
It even seems that the script is trying to block him, again.

**Comment by jsha** [comment]
Sorry about that! That does seem like a bad bug. Can you tell me your account name and your friend's account name so I can debug?

**Comment by ryulong** [comment]
I'm @ryulong and he's @sage_kun

**Comment by ryulong** [comment]
It seems to be checking his account every 5 minutes now.

**Comment by jsha** [comment]
Thanks for spotting this! I had been experimenting with a switch to http2 and accidentally deployed a version that used the http2 library, which caused the streaming component to crash repeatedly. Each time the streaming component restarts, it checks your recent mentions in case there were any it missed. This is why you see repeated enqueues of the block action. This is supposed to be harmless- they should continue to be canceled for following. I've reverted to an earlier version so that should no longer be an issue.

However, as you noticed, one action proceeded to block your friend even though you were following him. I notice another block action just a few minutes ago. Again, very sorry for that. I'm investigating it now and will let you know what I find.

**Comment by jsha** [comment]
After doing a bunch of investigating, I'm fairly confident the incorrect block actions were a side effect of the http2 library. Now that I've reverted that change, they shouldn't happen again. There are 50 accounts that appear to have been affected by this bug. I'm planning to review them tomorrow morning and reverse the blocks.

**Comment by jsha** [comment]
Summary:

For a few hours Saturday night, a bad deploy caused repeated auto-block attempts for users that have 'block new accounts' or 'block low follower accounts' options enabled. Those repeated auto-blocks were mostly fine, but for 41 users, Block Together blocked someone they follow, even though it's not supposed to. I've found each of those blocks and reversed them. Sorry for the error.

**Comment by ryulong** [comment]
Now that this was solved, I looked through the feed again and I'm still seeing entries for @sage_kun and another friend who has a low follower count show up like once a day. Is this normal behavior?
![http://puu.sh/i2i2L/ba7530e80b.png]

**Comment by jsha** [comment]
That is normal behavior, but I do get feedback that it is confusing to people. I've filed an issue to change the behavior: https://github.com/jsha/blocktogether/issues/194. Thanks again for your help catching this bug!
