### ISSUE TITLE
errors during mariadb provisioning

### ISSUE THREAD

**Issue by dunn** [jsha/blocktogether#210]
The provisioner is failing for me when it tries to start mysqld: https://gist.github.com/dunn/66a171f143d5e43706d6#file-vagrant-up-L460-L463

I tried setting up a Vagrant environment last year and it also failed during the DB setup, though it may have been at a different point.  Would you be open to moving to Ansible for the provisioning?  If so I'd be happy to help the migration.

**Comment by jsha** [comment]
Interesting. I do reproduce that same error. Weird, since I tested the
Vagrant build from scratch several times. I'll try to figure out how to fix.

I don't know much about Ansible. Unless it adds a significant amount of
value, I'd prefer not to add it, since it represents another piece of
technology I'd have to learn. My day job uses Salt, so if I was going to
learn a provisioning system I'd prefer it to be Salt. :-)

**Comment by dunn** [comment]
Thanks! Unfortunately the `chown` occurs before that user is created: https://gist.github.com/dunn/c6947b9c5e9bb0e83622#file-vagrant-up-L70

But removing that line and we're back to the original problem: https://gist.github.com/dunn/83b8f79499bf8c514c4d#file-vagrant-up-L457-L462

I don't know a lot about MySQL/MariaDB, but I tried `mkdir /var/run/mysqld` and that still failed, with an even less helpful message: https://gist.github.com/dunn/b4e45146f6e50cd9cf9d#file-vagrant-up-L460-L462

**Comment by jsha** [comment]
The issue turns out to be (in part) the custom MySQL configs I added for blocktogether (under the config/etc directory). They expect /data/mysql to exist, but at the time of running it doesn't. I'm working on a followup change now.

**Comment by jsha** [comment]
Ok, just pushed some changes to master that should fix the issue. Try again?

**Comment by dunn** [comment]
Seems like it, thanks!
