### ISSUE TITLE
Show accounts not blocked

### ISSUE THREAD

**Issue by WheresAlice** [jsha/blocktogether#230]
I would like to be able to see a list of accounts that should have been blocked but weren't because I was following them. This would help identify people I am following who are problematic according to the people I subscribe to.

Are there any privacy concerns in doing this? So long as this information is not shared with other users I can't immediately identify any issues in doing this.

**Comment by jsha** [comment]
Thanks for the suggestion. I don't plan to add a feature exactly like this, since I think it would encourage people to treat block lists as more authoritative than they often are. However, at some point I might add a feature to see, before you subscribe to a block list, which of your followings are on it. This might help people evaluate whether a given block list is appropriate for them.
