### ISSUE TITLE
Subscribers can't subscribe because the list is too big!

### ISSUE THREAD

**Issue by chiefcovfefe** [jsha/blocktogether#242]
My new subscribers can't subscribe because the list is too big. I add MANY bots and troll accounts daily, so my list is growing leaps and bounds. Please help so users can go back to subscribing! Thanks.

**Comment by JohnnyDemolition** [comment]
Translation:

I'm trying to kick everyone who disagrees with Louise Mensch off Twitter.  Please help!

**Comment by chiefcovfefe** [comment]
And now because of these jackasses you see exactly why its a problem and a needed bugfix ;)

-------- Original Message -------- On Sep 6, 2017, 3:59 PM, JohnnyDemolition wrote: Translation: I'm trying to kick everyone who disagrees with Louise Mensch off Twitter. Please help! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jsha** [comment]
The block list size limit is in place for two: To limit resource usage, and because very large block lists are typically curated by other automated tools rather than manually; in the second case, end-users are better off using those tools directly. I'm not planning to lift the limit anytime soon, sorry.

**Comment by chiefcovfefe** [comment]
Understood, thanks for the reply.
