### ISSUE TITLE
Blocking gone awry?

### ISSUE THREAD

**Issue by cray0n** [jsha/blocktogether#253]
Hi -- tried messaging on Twitter but perhaps this is a better place to raise this. My husband and I are both finding that our accounts are showing a lot of blocks that are categorized as "external" except neither of us have been blocking very much recently. My block list seems to have mushroomed by a large number since I logged in to Blocktogether a few days ago. 

Some of these blocks are verified accounts! I've gone through my apps attached to Twitter as well as login attempts and nothing looks fishy. So, for whatever reason, Block Together seems to be the source of these blocks. But I realize it doesn't quite make sense and . . . I don't know what to make of this. Help! Thanks.

**Comment by cray0n** [comment]
@znmeb how did you do the unblock all? By manually unblocking everyone in Twitter's "show me my block list"?

**Comment by jsha** [comment]
What's likely happening is this: When Block Together sees a block added to your account, it tries to figure out whether it was a block added due to a block list, or an "external" one (one that you added yourself, or another app). However, it only looks back one day to figure this out. So sometimes block list blocks get wrongly categorized as "external" when things are running slow. Were you subscribed to a block list? Have things settled out now? If not, feel free to reach out again on Twitter. Closing for now. Thanks!
